version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - yum install unzip -y
      - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
      - rm -rf terraform/
      - unzip terraform_"$TF_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform init -input=false -no-color
      - terraform workspace select $TF_WS -no-color
  build:
    commands:
      - terraform $TF_CMD $TF_OPT

  post_build:
    commands:
      - echo terraform $TF_CMD completed on `date`
